# Generated by Django 4.0.3 on 2023-07-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='m_img_url',
            field=models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/0/07/Nepal_logo.svg', max_length=500, unique=False),
            preserve_default=False,
        ),
    ]
