# Generated by Django 4.0.3 on 2023-07-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_m_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_img',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='uploads//'),
        ),
    ]
